// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MAdwg-9iwKB8A3GlTIiXDgdhrhD_JQ0',
    appId: '1:488096575546:web:1031ad4156aee79929c503',
    messagingSenderId: '488096575546',
    projectId: 'platableapp',
    authDomain: 'platableapp.firebaseapp.com',
    storageBucket: 'platableapp.appspot.com',
    measurementId: 'G-HWZZTRLVY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBYY2uqnlHjrOrT3qOaM4UOtYYjojC84',
    appId: '1:488096575546:android:863c635c0b7fcd3629c503',
    messagingSenderId: '488096575546',
    projectId: 'platableapp',
    storageBucket: 'platableapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnKTZjXj9suXLtk0iyAMgOkd9li3XBwM',
    appId: '1:488096575546:ios:e1bde9b209f4c67029c503',
    messagingSenderId: '488096575546',
    projectId: 'platableapp',
    storageBucket: 'platableapp.appspot.com',
    androidClientId: '488096575546-vo3ck0h3ak683i9ndtl8t0km4ot8e727.apps.googleusercontent.com',
    iosClientId: '488096575546-57go6hk9i3iro5g5tajjcohtepvh449g.apps.googleusercontent.com',
    iosBundleId: 'com.example.platableapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQnKTZjXj9suXLtk0iyAMgOkd9li3XBwM',
    appId: '1:488096575546:ios:7f88ef0fc8821b3b29c503',
    messagingSenderId: '488096575546',
    projectId: 'platableapp',
    storageBucket: 'platableapp.appspot.com',
    androidClientId: '488096575546-vo3ck0h3ak683i9ndtl8t0km4ot8e727.apps.googleusercontent.com',
    iosClientId: '488096575546-r3ddn2fcl6ds917l257ocj2pb84o16j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.platableapp.RunnerTests',
  );
}
